# -*- coding: utf-8 -*-
"""ocr text extraction from image .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GaTNYTbky3kwWpNDbhtw1VAHX5vkspPH
"""

!pip install easyocr

import numpy as np
import matplotlib.pyplot as plt
import cv2
import easyocr
from pylab import rcParams
from IPython.display import Image
rcParams['figure.figsize'] = 8, 16

reader = easyocr.Reader(['en'])

Image("c.PNG")

output = reader.readtext('c.PNG')

output

cord = output[-1][0]

x_min, y_min = [int(min(idx)) for idx in zip(*cord)]

x_max, y_max = [int(max(idx)) for idx in zip(*cord)]

image = cv2.imread('c.PNG')
cv2.rectangle(image,(x_min,y_min),(x_max,y_max),(0,0,255),2)
plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))

a=reader.readtext(image)

arr=np.asarray(a)
arr



# manually writing the output got from previous operation
""" adani AARTEK ADI?OIT amazon TnT^ aeanu amdocs AVELON nl5fBLI Apollo AXIS BANK falsaamlr Munich BYJUS OIT(IIMIOTEh C+deVital Capitalva BiTiBe consuliadd Compunnel cure ft Collabeia Cognizant DISPARX ybarsoft
 @s Imun honar GHARBIMGER evitamins evivehke JOHNsoN 5grm0L HSBC noruTT icicllfII ICICI Bank ICICI Securities indliar
KAIVYI KEC Ilnfol entnid Isr Induslnd impetus Lluratia ooreorun9 linkiTes Mphasis myMO MyAnatomy LLO IT stalMDan Ra Splash techracers skillventory
TekLinl Soucol YASH XALT worldpay IValueLabs ilL5 uuIT
"""
adani,AARTEK,ADI?OIT,amazon,TnT^,aeanu,amdocs,AVELON,nl5fBLI,Apollo,AXIS,BANK,falsaamlr,Munich,BYJUS,OIT(IIMIOTEh,C+deVital,Capitalva,BiTiBe,consuliadd,Compunnel,cure,ft,Collabeia,Cognizant,DISPARX,ybarsoft
,@s,Imun,honar,GHARBIMGER,evitamins,evivehke,JOHNsoN,5grm0L,HSBC,noruTT,icicllfII,ICICI,Bank,ICICI,Securities,indliar
KAIVYI,KEC,Ilnfol,entnid,Isr,Induslnd,impetus,Lluratia,ooreorun9,linkiTes,Mphasis,myMO,MyAnatomy,LLO,IT,stalMDan,Ra,Splash,techracers,skillventory
TekLinl,Soucol,YASH,XALT,worldpay,IValueLabs,ilL5,uuIT